[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Indian_Beauty_Shop_Marketing_Analytics"
version = "0.0.1"
description = "A short description of the project."
authors = [
  { name = "Quan" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
requires-python = "~=3.10.0"


[tool.ruff]
line-length = 99
src = ["Indian_Beauty_Shop_Marketing_Analytics"]
include = ["pyproject.toml", "Indian_Beauty_Shop_Marketing_Analytics/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["Indian_Beauty_Shop_Marketing_Analytics"]
force-sort-within-sections = true

